#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -Eeuo pipefail

exit_code="${1:-1}"
if [[ "${exit_code}" -ne 0 && "${exit_code}" -ne 256 ]]; then
    echo "Reolink FTPS Server stopped with exit code ${exit_code}" >&2
    echo "${exit_code}" > /run/s6-linux-init-container-results/exitcode
    exec /run/s6/basedir/bin/halt
fi
